# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
env:
- FLASK_APP=autoapp.py FLASK_DEBUG=1
python:
  - 3.6
  - 3.7
install:
  - pip install -r requirements/dev.txt
  - nvm install 10
  - nvm use 10
  - npm install
before_script:
  - npm run lint
  - npm run build
  - flask lint --check
script: flask test
